name: Build And Deploy To Tencent ECS

on:                               
  push:
    branches: [ "main" ]

jobs:                             
  build-and-deploy:
    runs-on: ubuntu-latest  
      
    steps:                        
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build

    - name: Deploy to tencent server        
      uses: easingthemes/ssh-deploy@v3.0.0      
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }} 
        ARGS: "-avzr --delete"
        SOURCE: "dist/*"
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USER }}
        TARGET: "/var/www/unity/"